services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123" 
      - "9000:9000"  
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=sales_db
      - CLICKHOUSE_USER=default

  clickhouse-client:
    image: yandex/clickhouse-client:latest
    depends_on:
      - clickhouse
    entrypoint: /bin/sh -c "echo 'ClickHouse client container started!' && tail -f /dev/null"
  
  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    volumes:
      - ./metabase_plugins:/plugins
      - ./metabase-data:/metabase-data  
    environment:
      - MB_PLUGINS_DIR=/plugins
      - MB_DB_FILE=/metabase-data/metabase.db
    depends_on:
      - clickhouse

volumes:
  clickhouse_data:
  metabase_data:
